Revert "Run Snyk without reporting to central server"
This reverts commit 47c7585965d277f0876bf57bea24d60a014d2e3f.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -373,40 +373,33 @@ jobs:
           command: openapi_tests
 
   #Snyk tests
-test-snyk:
-  <<: *job-defaults
-  executor:
-    name: docker-builder
-    resource_class: large
-  steps:
-    - setup_docker:
-        docker_layer_caching: true
-    - checkout
-    - restore-build-cache
-    - install-build-dependencies
-    - run-build-step:
-        step-name: Assemble rundeck
-        command: rundeck_assemble_build
-    - snyk/install
-    - run-build-step:
-        step-name: Configure Snyk
-        command: snyk config set org='rundeck-core-mtgfa3XPaKGbFtHj9aRXhg'
-    - run-build-step:
-        step-name: Run Snyk monitors to track vulnerabilities
-        command: |
-          if [ "$CIRCLE_BRANCH" = "main" ]; then
-            snyk monitor --all-projects --detection-depth=10 --scan-all-unmanaged
-          else
-            echo "Skipping monitor for non-main branch"
-          fi
-    - run-build-step:
-        step-name: Run Snyk test
-        command: |
-          if [ "$CIRCLE_BRANCH" = "main" ]; then
-            snyk test --severity-threshold=high --all-projects --detection-depth=10 --scan-all-unmanaged || true
-          else
-            snyk test --severity-threshold=high --all-projects --detection-depth=10 --scan-all-unmanaged --report=false || true
-          fi
+  test-snyk:
+    <<: *job-defaults
+    executor:
+      name: docker-builder
+      resource_class: large
+    steps:
+      - setup_docker:
+          docker_layer_caching: true
+      - checkout
+      - restore-build-cache
+      - install-build-dependencies
+      - run-build-step:
+          step-name: Assemble rundeck
+          command: rundeck_assemble_build
+      - snyk/install
+      - run-build-step:
+          step-name: Configure Snyk
+          # this will need to be updated if the project changes owners
+          command: snyk config set org='rundeck-core-mtgfa3XPaKGbFtHj9aRXhg'
+      - run-build-step:
+          step-name: Run Snyk monitors to track vulnerabilities
+          # Run monitor first to push results to webui
+          command: snyk monitor --all-projects --detection-depth=10 --scan-all-unmanaged
+      - run-build-step:
+          step-name: Run Snyk test (ignoring scan results)
+          # Don't fail the build giving the Core team some time to clean the repo using the monitors
+          command: snyk test --severity-threshold=high --all-projects --detection-depth=10 --scan-all-unmanaged || true
 
   # Trigger pipeline in the enterprise repo
   trigger-enterprise:
@@ -728,6 +721,8 @@ workflows:
           context:
             - Snyk
             - Cloudsmith
+          filters:
+            branches: { only: main }
       - wizcli-scan:
           name: WizCLI Scan Preview
           <<: *require-build
